### PR TITLE
Update 20220830 for sony aosp 11

### PR DESCRIPTION
**Pull request by mkosola**

### CODE REVIEW

**Comment by mkosola** [comment]
This replace https://github.com/mer-hybris/android/pull/162

**Review by Thaodan — APPROVED** [review]
LGTM

**Review by sledges — CHANGES_REQUESTED** [review]
Please format this commit as the rest in this repo `[sony-common] Fix device/sony/common hash.`

**Comment by sledges** [comment]
Also Change-Id is not required.

**Comment by mkosola** [comment]
> Please format this commit as the rest in this repo `[sony-common] Fix device/sony/common hash.`

Fixed

**Review by sledges — APPROVED** [review]

**Pull request merged**
