### PR TITLE
[sony-nile] Update manifest. JB#42770, MER#1948, MER#1947

### PR DESCRIPTION
**Pull request by krnlyng**
[rpm] after dsp folder fix we can fix this path. JB#42774
[kernel] Merge upstream changes. JB#42213
[system/core] (hybris) ignore "mount" and "mkdir /tmp" commands entirely. JB#42770
[device/sony/common] Do not create the dsp directory since it is created by all platforms which need it, as a symlink. JB#42774
[device/sony/nile] (hybris) Remove duplicate vendor mountpoint and add back odm mountpoint. MER#1948
[hybris/hybris-boot] Adapt pioneer mountpoints to upstream changes. MER#1948
[hybris/hybris-boot] Build bootctl for Android 8. MER#1947

Upstream changes:

[vendor/nxp/NXPNFCC_FW] NFC_NCIHALx_AR2000.09.00.0D_OpnSrc
[vendor/nxp/NXPNFCC_FW] Update README.md
[vendor/nxp/NXPNFCC_FW] Update README.md
[vendor/nxp/NXPNFCC_FW] Update README.md
[vendor/nxp/NXPNFCC_FW] NFC_NCIHALx_AR2000.09.00.0A_OpnSrc
[vendor/nxp/NXPNFCC_FW] NFC_NCIHALx_AR0800.9.0.10
[vendor/qcom/opensource/camera] CameraParameters: fix build with BOARD_VNDK_VERSION
[vendor/qcom/opensource/camera] msm8998: Update from AOSP
[vendor/qcom/opensource/camera] Revert "QCamera2:HAL :Changes to get the vsync event and presentation timestamp"
[vendor/qcom/opensource/camera] Revert "QCamera2:Compilation fix for OMR release"
[vendor/qcom/opensource/camera] Revert "QCamera2:QCameraDisplay:Merging fix of DisplayService transaction failed."
[vendor/qcom/opensource/camera] Revert "QCamera2:QCameraDisplay:Dynamic registration of display service."
[vendor/qcom/opensource/camera] fix display folder path
[vendor/qcom/opensource/camera] Fix dependencies for mm-camera-interface
[vendor/qcom/opensource/camera] fix build with BOARD_VNDK_VERSION
[vendor/qcom/opensource/camera] camera: fix build with BOARD_VNDK_VERSION
[vendor/qcom/opensource/camera] move the camera dumps to /data/vendor/camera
[vendor/qcom/opensource/camera] mm-camera: Change kernel version check for SoMC
[vendor/qcom/opensource/camera] QCamera2: HAL: Change media entity enumeration logic. Issue: Media entity enumeration logic not support kernel 4.9 Fix: Changes added to support media entity enumeration for both Kernel 4.9 and 4.4 version.
[device/sony/akari] reorder properties for DS devices
[device/sony/akari] remove prebuilt dtbo.img when TARGET_COMPILE_WITH_MSM_KERNEL is true
[device/sony/akari] set GSM capability for DS devices
[device/sony/apollo] reorder properties for DS devices
[device/sony/apollo] remove prebuilt dtbo.img when TARGET_COMPILE_WITH_MSM_KERNEL is true
[device/sony/apollo] remove unused Sensors Configuration
[device/sony/apollo] set GSM capability for DS devices
[device/sony/common] treble: add the packages needed for BOARD_VNDK_VERSION
[device/sony/common] vendor: increment vendor version
[device/sony/common] librqbalance: fix build with BOARD_VNDK_VERSION
[device/sony/common] power: fix build with BOARD_VNDK_VERSION
[device/sony/common] libpolyreg: Fix libcutils private headers
[device/sony/common] move the camera dumps to /data/vendor/camera
[device/sony/common] Revert "cnss-daemon.rc: set net_admin for cnss-daemon"
[device/sony/common] vendor: init: Add paths for k4.9
[device/sony/common] move the common SRC_CAMERA_HAL_DIR
[device/sony/common] data: add the configuration for sdm845
[device/sony/common] odm: packages: add sensors.sdm845
[device/sony/common] add cdsprcpd service
[device/sony/common] init.common.rc: Create dir for display
[device/sony/common] cnss-daemon.rc: set net_admin for cnss-daemon
[device/sony/common] switch Display HAL to our own branch
[device/sony/discovery] reorder properties for DS devices
[device/sony/discovery] set GSM capability for DS devices
[device/sony/dora] reorder properties for DS devices
[device/sony/kagura] reorder properties for DS devices
[device/sony/keyaki] reorder properties for DS devices
[device/sony/loire] remove the duplicate androidboot.console
[device/sony/loire] genfs_contexts: fix duplicate path
[device/sony/loire] init: Add paths for k4.9
[device/sony/loire] uevent: Add paths for k4.9
[device/sony/loire] platform: Add paths for k4.9
[device/sony/loire] sepolicy: Add paths for k4.9
[device/sony/maple] reorder properties for DS devices
[device/sony/pioneer] reorder properties for DS devices
[device/sony/pioneer] set GSM capability for DS devices
[device/sony/poplar] reorder properties for DS devices
[device/sony/sepolicy] sepolicy: avoid kernel 4.9 denials
[device/sony/sepolicy] sepolicy: avoid kernel 4.9 denials
[device/sony/sepolicy] sepolicy: avoid kernel 4.9 denials
[device/sony/sepolicy] sepolicy: Add paths for k4.9
[device/sony/sepolicy] add basic cdsprpcd permisisons
[device/sony/suzu] reorder properties for DS devices
[device/sony/tama] add A/B OTA dexopt support
[device/sony/tama] add PRODUCT_STATIC_BOOT_CONTROL_HAL
[device/sony/tama] ueventd.rc: Update paths for kernel 4.9
[device/sony/tama] remove the duplicate androidboot.console
[device/sony/tama] genfs_contexts: remove duplicate rmtfs_sharedmem
[device/sony/tone] sepolicy: avoid sde denials
[device/sony/tone] remove the duplicate androidboot.console
[device/sony/tone] genfs_contexts: remove duplicate sysfs_mdss_mdp_caps
[device/sony/tone] init: Add paths for k4.9
[device/sony/tone] platform: Add paths for k4.9
[device/sony/tone] ueventd: Add paths for k4.9
[device/sony/tone] sepolicy: Add paths for k4.9
[device/sony/yoshino] remove the duplicate androidboot.console
[device/sony/yoshino] sepolicy: Add paths for k4.9
[device/sony/yoshino] ueventd: Add paths for k4.9
[packages/apps/ExtendedSettings] ES: Migrate to AAPT2
[packages/apps/ExtendedSettings] ES: preference framework has moved out of v7 folder.
[packages/apps/ExtendedSettings] ES: Using private APIs does not require SDK guard.
[packages/apps/ExtendedSettings] ES: Grant access to private SDK APIs such as SystemProperties.
[packages/apps/ExtendedSettings] ES: set LOCAL_SDK_VERSION to current
[hardware/qcom/bt] bt: use TARGET_BOARD_AUTO to override qcom hals
[hardware/qcom/bt] bt: use TARGET_BOARD_AUTO to override qcom hals
[vendor/oss/repo_update] Сode alignment and duplicate removal
[vendor/oss/repo_update] Add support for exFAT file system to vold
[vendor/oss/repo_update] Fix bug Device that can't support adoptable storage cannot read the sdcard
[vendor/oss/repo_update] repo_update: Add odm check
[vendor/oss/repo_update] Revert "repo_update: Properly fetch and apply recovery "rotation logic""
[vendor/oss/repo_update] media: msm8996: bump 713242 patch version
[vendor/oss/repo_update] Add display HAL patch for night mode
[vendor/oss/repo_update] msm8996: fix build
[vendor/oss/repo_update] Add patches required to build using sdm845 hals and 4.9 kernel headers
[vendor/oss/timekeep] Don't use shell in make file
[vendor/oss/timekeep] Let TimeKeep use private platform APIs
[vendor/oss/timekeep] Timekeep: set LOCAL_SDK_VERSION to current
[vendor/oss/timekeep] fix build with BOARD_VNDK_VERSION
[vendor/oss/transpower] Bump up version (2.2.1)
[vendor/oss/transpower] Fix access to telephony-common lib and additional resources
[vendor/oss/transpower] Require access to hidden platform APIs
[vendor/oss/transpower] Bump app version (2.1.1)
[vendor/qcom/opensource/location] silence LOG_TAG macro redefined warning
[vendor/qcom/opensource/location] loc_api: include: Correct pointer type of message_table
[vendor/qcom/opensource/location] Revert "Speed, bearing and vertical accuracy must be read from Zpp Fix"
[vendor/qcom/opensource/location] fix build with BOARD_VNDK_VERSION
[kernel/sony/msm-4.4/kernel/drivers/staging/wlan-qc/qcacld-3.0] Android.mk: add SOMC_KERNEL_VERSION
[vendor/oss/cash] silence LOG_TAG macro redefined warning
[vendor/oss/cash] remove unused variables
[vendor/oss/cash] fix build with BOARD_VNDK_VERSION
[vendor/oss/fingerprint] Android.mk: Use SOMC_KERNEL_VERSION for path selection
[vendor/oss/fingerprint] Android.mk: Update sysfs path for k4.9
[vendor/oss/fingerprint] Fix warnings of unused parameters and variables
[vendor/oss/fingerprint] Remove cpp flags
[vendor/oss/projection] add LOCAL_PRIVATE_PLATFORM_APIS
[vendor/oss/projection] remove unused variables
[vendor/oss/projection] REVERTME: remove Android.bp

Change-Id: I67796aefac706378248cd01ee1ef816de8efa2bf
Signed-off-by: Franz-Josef Haider <franz.haider@jolla.com>

### CODE REVIEW

**Review by mkosola — APPROVED** [review]

**Comment by sledges** [comment]
I'd say bugref MER#1948 is more apropriate, as it fixes more than just services on boot

**Comment by sledges** [comment]
Ok, i only checked the PR title, which had that JB ;) all good within commits!

**Review by mlehtima — APPROVED** [review]

**Comment by krnlyng** [comment]
missing some kernel changes from upstream, will update.

**Review by sledges — APPROVED** [review]

**Comment by mlehtima** [comment]
Still looks good after kernel repo update.

**Review by sledges — APPROVED** [review]
Yes, now android_kernel_sony_msm has the correct hash to the just-merged PR up there

**Comment by krnlyng** [comment]
I sneaked in one more change from upstream (dsp folder fix).

**Comment by krnlyng** [comment]
and another one related to that, will test the result.

**Comment by krnlyng** [comment]
works as expected.

**Pull request merged**
