### PR TITLE
droid-src: hybris:  Do not log battery status to kernel log

### PR DESCRIPTION
**Pull request by Thaodan**

### CODE REVIEW

**Comment by sledges** [comment]
I suggest to do manifest update, because this PR warrants a rebuild of system anyway.
You can take it from https://github.com/thaodan/android/compare/sony-aosp-11-jb58062...sledges:sony-aosp-11-jb58062?expand=1

**Comment by sledges** [comment]
Nitpick (one can't spot that via github webview:)
```diff
-droid-src: hybris: Do not log battery status to kernel log
+droid-src: hybris:  Do not log battery status to kernel log
```
and `[hybri]` -> `[hybris]`.

**Comment by Thaodan** [comment]
> I suggest to do manifest update, because this PR warrants a rebuild of system anyway. You can take it from https://github.com/thaodan/android/compare/sony-aosp-11-jb58062...sledges:sony-aosp-11-jb58062?expand=1

I added your comment and removed the incompatible with lena flag since comment and since all the paths in that folder wrong for 
past 2021 devices (e.g. Lena, Edo and Sagami):
https://github.com/sonyxperiadev/device-sony-common/pull/889#issuecomment-1123294591

**Comment by mkosola** [comment]
These changes were part of https://github.com/mer-hybris/android/pull/163

**Comment by mkosola** [comment]
Ah, sorry, mixed PRs, will reopen this

**Comment by Thaodan** [comment]
Replaced by #166.

**Pull request closed without merging**
