### PR TITLE
droid-src: update manifest from sony upstream

### PR DESCRIPTION
**Pull request by krnlyng**
[droid-src] update manifest from sony upstream. JB#54990, JB#54347

Change-Id: I13e13658b35b3a0a88d28510cba4efe734ee2e2b

### CODE REVIEW

**Review by sledges — APPROVED** [review]
Please tag to align around the same time as droid-system gets rebuilt

**Comment by krnlyng** [comment]
> Please tag to align around the same time as droid-system gets rebuilt

I have but one question: how did you generate the tagged-manifest.xml in the past? I did it using "repo diffmanifests" and manually editing the tagged-manifest.xml. Do you have an automated way?

**Comment by krnlyng** [comment]
> > Please tag to align around the same time as droid-system gets rebuilt
> 
> I have but one question: how did you generate the tagged-manifest.xml in the past? I did it using "repo diffmanifests" and manually editing the tagged-manifest.xml. Do you have an automated way?

Other than "repo manifest -o" because that produces different output.

**Comment by sledges** [comment]
> > I have but one question: how did you generate the tagged-manifest.xml in the past? Do you have an automated way?
>
> Other than "repo manifest -o" because that produces different output.

Different output is produced on host's repo (I suspect LC_* and sorting:) -- groups attribute is moved forwards.
On HABUILD_SDK (ubu-focal chroot) order of attributes is preserved to the currently used format ('groups' at the end).

If you need a quick'n'dirty solution:) https://github.com/mer-hybris/android/pull/132#issuecomment-818004278

**Comment by krnlyng** [comment]
My PR got closed for some reason (i didn't do it) and i cannot reopen it apparently. I filed a new one #138.

**Pull request closed without merging**
